### PR TITLE
Set up minimal maven version. 3.3.x 

### PR DESCRIPTION
**Pull request by skabashnyuk**
it will allow to provide default jvm settings  and ensure that users is using it.

### CODE REVIEW

**Comment by benoitf** [comment]
I don't think we should ask the latest one as minimal

**Comment by benoitf** [comment]
3.3.x doesn't imply 3.3.9

**Comment by skabashnyuk** [comment]
what version do you propose? 
How it's better when 3.3.9?

**Comment by benoitf** [comment]
3.3.1 ?

**Comment by skabashnyuk** [comment]
looks like a matter of taste. :) Is there any technical reason? 
I would like to have fresh version when we goes to Ecliple community.
From stability point of view 3.3.1 is looks the same for me as 3.3.9

**Comment by benoitf** [comment]
Mainly it's better to not force ppl to upgrade their maven version as long as it works.
so by using 3.3.1, it ensures ppl with 3.3.1, 3.3.3 and 3.3.9 can compile Che

**Comment by skabashnyuk** [comment]
My motivation is a bit different. 3.3.9 can provide as a longer base for future. Users can update maven only once and use it.

**Comment by vparfonov** [comment]
ok

**Comment by benoitf** [comment]
Future is 3.4.x or another version

when requiring a version, you require the lower digit of the major version

this is what was described in the issue title
3.3.x imply 3.3.1 not 3.3.9

**Comment by riuvshin** [comment]
+1 to update to latest (currently we are on 3.3.3)

**Comment by benoitf** [comment]
I'm +1 with 3.3.x then it means 3.3.1 (so ppl with 3.3.1 and 3.3.3 can also work with it)

**Comment by riuvshin** [comment]
So let's set it to 3.3.3 as it's exactly version which is set on CI and release env. WDYT?

**Comment by benoitf** [comment]
3.3.3 may be OK as release dates were close (3.3.1 and 3.3.3) but there is no technical issue preventing to use 3.3.1
3.3.1 is minimal while latest version is the prefered one

**Comment by skabashnyuk** [comment]
I've updated pr to 3.3.1 @riuvshin will merge it as soon as it will be ok for release cycle.

**Pull request merged**
